apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-f
spec:
  selector:
    matchLabels:
      app: node-f
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: node-f
        tier: backend
        track: stable
    spec:
      containers:
        - name: node-f
          image: 426565272619.dkr.ecr.us-east-2.amazonaws.com/freydin:node-f.1
          ports:
            - name: node8080
              containerPort: 8080
