apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    type: local	
spec:
  capacity:
    storage: 8Gi
#  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
#  mountOptions:
#    - hard
#    - nfsvers=4.1
  hostPath: 
    path: /home/user/work/src/nginx/volume
#    server 172.17.0.1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: webpub-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

