apiVersion: v1
kind: Service
metadata:
  name: node-f
spec:
  selector:
    app: node-f
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: node8080
#      nodePort: 30002
#  type: NodePort
#  type: LoadBalancer
